[[experience]]
company = "Milwaukee Tools"
position = "Advanced Manufacturing Design Intern"
timeline = "May. 2026 - August. 2026"

[[experience.project]]
type = "small"
total_rows = 1
total_cols = 2
bg_color="#be1515ff"
border_color="#be1515ff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 1
type = "image"
content="IMG_4569.JPG"

[[experience.project.grid_item]]
rows = 1
cols = 1
type = "text"
content="During my internship at Milwaukee Tool, I developed a proof-of-concept machine to improve the Big Hawg hole saw manufacturing process at the request of the NPD team. The primary challenge was reliably locating and orienting complex geometric components for assembly. I developed a custom pick-and-place system to automate this process, iterating through mechanism designs and testing to improve speed and repeatability. The final concept INCREASING MANUFACTURING THROUGHPUT BY 80% compared to manual assembly.\n\n I also adapted vibratory feeder-bowl technology for a new product assembly line, expanding my experience with high-volume part feeding, orientation, and manufacturing automation."

[[experience]]
company = "Shurhold.Ind"
position = "Factory Intern"
timeline = "May. 2025 - Aug. 2025"

[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#c86e6eff"
border_color="#c86e6eff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Adjustable Mounting Table"

[[experience.project.grid_item]]
rows = 6
cols = 4
type = "model"
content="XY_TableMove.glb"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="In the brush machining process, an industrial ink printer applies the logo to the brush blocks. Different brush models require unique alignments. Designed with two linear actuators, this new mounting table can reposition the 200lb printer to preset coordinates on both the X- and Y-axes. The setup efficiency and repeatability were improved by 60%"


[[experience.project.grid_item]]
rows = 3
cols = 2
type = "image"
content="Table.png"


[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#c86e6eff"
border_color="#c86e6eff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Water Sprite Mop Splitter"

[[experience.project.grid_item]]
rows = 6
cols = 4
type = "model"
content="MopSlitterCut2.glb"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="Automated the water sprite mop cutting process. Before I joined the team, they were using a rollerblade alignment that required a high level of force to operate. Now, employees of all levels of strength can operate; production is increased by 66% by being able to cut 3 mops at once, and the cuts are more consistent compared to human errors."

[[experience.project.grid_item]]
rows = 3
cols = 2
type = "image"
content="Mop.png"


[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#c86e6eff"
border_color="#c86e6eff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Bucket Hole Punch"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="BP1.png"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="BP2.png"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="Reverse-engineered the Shurhold bucket punch machine. Drafted up-to-date documentation, parts list, CAD models, and engineering drawings. These are now available to replace broken components as needed."

[[experience.project.grid_item]]
rows = 4
cols = 4
type = "model"
content="bucket_punch.glb"

[[experience.project.grid_item]]
rows = 3
cols = 2
type = "image"
content="BPlive.jpeg"



[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#c86e6eff"
border_color="#c86e6eff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Brush Bumper Installation"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="""Nicknamed "Steve" by the factory crew, this dual-piston bumper installer streamlined the assembly of rubber bumpers onto multiple brush models. Designed to stretch and snap the band on fresh brushes. Replaced an outdated system and decreased assembly time by 25%."""

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="BB2.png"

[[experience.project.grid_item]]
rows = 5
cols = 2
type = "image"
content="BB1.png"

[[experience.project.grid_item]]
rows = 4
cols = 4
type = "model"
content="brushassembaly.glb"

[[experience.project]]
type = "small"
total_rows = 6
total_cols = 6
bg_color="#c86e6eff"
border_color="#c86e6eff"
shadow_color="#FF0000"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Office Layout"

[[experience.project.grid_item]]
rows = 2
cols = 4
type = "text"
content="Worked alongside architects and construction workers to draft a layout, primarily utilizing AutoCAD, for the addition of two new offices. Optimized for ease of access and staff communication."

[[experience.project.grid_item]]
rows = 5
cols = 2
type = "image"
content="OF1.png"

[[experience.project.grid_item]]
rows = 4
cols = 2
type = "image"
content="OF2.jpg"

[[experience.project.grid_item]]
rows = 4
cols = 2
type = "image"
content="OF3.jpg"


[[experience]]
company = "Lineage Biomedical"
position = "Intern"
timeline = "May. 2024 - July. 2024"

[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#73a4d0ff"
border_color="#73a4d0ff"
shadow_color="#00b3ffff"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Nava-Click"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="LB4.png"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="LB1.png"

[[experience.project.grid_item]]
rows = 3
cols = 2
type = "image"
content="NovaClick.png"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="Process: Observed a product to redesign in CAD Fusion 360. Critical decisions to maximize functionality & realism while minimizing manufacturing difficulty. Communicate with the company for an optimal outcome."

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="LB2.png"

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="Working for Lineage Biomedical, I redesigned their existing product in CAD to produce a 10x scaled model to show at trade shows. During the design process, I considered several factors, including transportation, manufacturing costs, and durability. I also contributed my experience in 3D printing to aid in manufacturing."

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content="Materials: 3D-printed PLA, TPU, & other Wood. The right three pictures demonstrate different viewing layers of the sarringe mechanism."

[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content="LB3.png"


[[experience]]
company = "Bikes Plus"
position = "Bike Mechanic"
timeline = "November. 2020 - October. 2023"

[[experience.project]]
type = "small"
total_rows = 6
total_cols = 6
bg_color="#7acc93ff"
border_color="#7acc93ff"
shadow_color="#00d13fff"

[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Bike Mechanic"

[[experience.project.grid_item]]
rows = 6
cols = 2
type = "image"
content="Bike1.jpg"

[[experience.project.grid_item]]
rows = 6
cols = 2
type = "image"
content="Bike2.jpg"

[[experience.project.grid_item]]
rows = 5
cols = 2
type = "text"
content="Working at Bikes Plus I gained skills as a mechanic learning the ins and outs of bike functionality. One of my favorite projects was frame swapping a Canyon Neuron CF8. Process: disassembled and stripped all components off the old frame including suspension, derailer, brakes, handlebars, and wheels. Cleaned and fixed old parts assembling them back onto the new frame. Truing the new bike to the customer's attributes."