[[project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#819bb5ff"
border_color="#819bb5ff"
shadow_color="#819bb5ff"

[[project.grid_item]]
rows = 1
cols = 2
type = "title"
content = "Bone Yard"

[[project.grid_item]]
rows = 1
cols = 2
type = "text"
content="For more detail watch this awesome video:"

[[project.grid_item]]
rows = 3
cols = 2
type = "video"
content = "https://youtu.be/2SjGUhyXE9I"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "1) Using paper and pencil, I sketched different obstacle designs and configurations"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "2) Built the base frame and flipper system, leaving a beautiful playboard canvas to build upon"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "3) Continued to make modifications around space constraints and available angles"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "4) Decorated the pinball machine in a Halloween theme. Featuring one main skeleton posing as an antagonist in your pinball adventures"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballStart.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballBoard.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PathSketch.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballFinished.png"

[[project.grid_item]]
rows = 3
cols = 2
type = "text"
content = "Halloween-themed pinball machine named Bone Yard. Self-designed featuring 3 functioning flippers, a coin intake, a bonus ball, and over 14 obstacles. Medium: cardboard, coat hangers, plastic scraps, 3D parts, rubber bands, popstical sticks, and halloween decoration"


[[project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#b5818cff"
border_color="#b5818cff"
shadow_color="#b5818cff"

[[project.grid_item]]
rows = 1
cols = 2
type = "title"
content = "Cloudjumber"

[[project.grid_item]]
rows = 1
cols = 2
type = "text"
content="For more detail watch this awesome video:"

[[project.grid_item]]
rows = 3
cols = 2
type = "video"
content = "VACV14ON9QE"

[[project.grid_item]]
rows = 3
cols = 2
type = "text"
content = "PROJECT DISCRIPTION: Final Design Project challenged teams to develop an autonomous machine for a 40-second, head-to-head competition themed around How to Train Your Dragon. The machine could score points by completing four primary tasks: extinguishing a fire, collecting and sorting fish and eels, returning sheep to designated paddocks, and moving torches to light a bonfire, all while meeting strict size, energy, cost, and operational constraints."

[[project.grid_item]]
rows = 3
cols = 2
type = "image"
content = "ME2110Group.png"

[[project.grid_item]]
rows = 3
cols = 2
type = "pdf"
content = "ME 2110 - A10 - Team 5 - Final Project Report.pdf"

[[project.grid_item]]
rows = 2
cols = 4
type = "text"
content = "TEAM APPROACH: Our team prioritized reliable, repeatable mechanisms capable of scoring across all five tasks. The final robot integrated a drivetrain, telescoping boom, scissor arms, sheep deployment, and fish/eel sorting system into a compact autonomous platform. Through iterative prototyping and testing, the robot achieved the 3rd-highest average score of 156 points per run among 70 teams."


[[project]]
type = "small"
total_rows = 6
total_cols = 6
bg_color="#3e2b3aff"
Border_color="#3e2b3aff"
shadow_color="#3e2b3aff"

[[project.grid_item]]
rows = 1
cols = 2
type = "title"
content = "Casino Watch"

[[project.grid_item]]
rows = 3
cols = 2
type = "text"
content = "Inspired by my love of cards, this watch combines a simplistic look with a unique twist. The hour hand is a fan of cards that rotate so the top card always represents the hour. The minute hand is double sided black and read reviling one at a time representing AM/PM over the cards."

[[project.grid_item]]
rows = 6
cols = 2
type = "image"
content = "Watch.png"

[[project.grid_item]]
rows = 5
cols = 2
type = "model"
content = "watchassembaly10x.glb"

[[project.grid_item]]
rows = 3
cols = 1
type = "text"
content = "Medium:  Plastic watch base, 3D printed retainers, face, and hand, glass/plastic cover"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "OpenWatch.png"