[[project]]
type = "large"
total_rows = 6
total_cols = 6
bg_color="#819bb5ff"
border_color="#819bb5ff"
shadow_color="#819bb5ff"

[[project.grid_item]]
rows = 1
cols = 2
type = "title"
content = "Bone Yard"

[[project.grid_item]]
rows = 1
cols = 2
type = "text"
content="For more detail watch this awesome video:"

[[project.grid_item]]
rows = 3
cols = 2
type = "video"
content = "https://youtu.be/2SjGUhyXE9I"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "1) Using paper and pencil, I sketched different obstacle designs and configurations"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "2) Built the base frame and flipper system, leaving a beautiful playboard canvas to build upon"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "3) Continued to make modifications around space constraints and available angles"

[[project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "4) Decorated the pinball machine in a Halloween theme. Featuring one main skeleton posing as an antagonist in your pinball adventures"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballStart.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballBoard.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PathSketch.png"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "PinballFinished.png"

[[project.grid_item]]
rows = 3
cols = 2
type = "text"
content = "Halloween-themed pinball machine named Bone Yard. Self-designed featuring 3 functioning flippers, a coin intake, a bonus ball, and over 14 obstacles. Medium: cardboard, coat hangers, plastic scraps, 3D parts, rubber bands, popstical sticks, and halloween decoration"


[[project]]
type = "small"
total_rows = 6
total_cols = 6
bg_color="#3e2b3aff"
Border_color="#3e2b3aff"
shadow_color="#3e2b3aff"

[[project.grid_item]]
rows = 1
cols = 2
type = "title"
content = "Casino Watch"

[[project.grid_item]]
rows = 3
cols = 2
type = "text"
content = "Inspired by my love of cards, this watch combines a simplistic look with a unique twist. The hour hand is a fan of cards that rotate so the top card always represents the hour. The minute hand is double sided black and read reviling one at a time representing AM/PM over the cards."

[[project.grid_item]]
rows = 6
cols = 2
type = "image"
content = "Watch.png"

[[project.grid_item]]
rows = 5
cols = 2
type = "model"
content = "watchassembaly10x.glb"

[[project.grid_item]]
rows = 3
cols = 1
type = "text"
content = "Medium:  Plastic watch base, 3D printed retainers, face, and hand, glass/plastic cover"

[[project.grid_item]]
rows = 3
cols = 1
type = "image"
content = "OpenWatch.png"