title="Vaughn Berhoff's Portfolio" 
icon="material-symbols:web-sharp"

[navigation.profile]
enabled=true
name="Vaughn Berhoff"
icon="devicon:bash"

[navigation.projects]
enabled=true
name="Projects"
icon="material-symbols:folder-code-outline"

[navigation.experience]
enabled=true
name="Experience"
icon="material-symbols:work-outline"

[navigation.skills]
enabled=true
name="Skills"
icon="game-icons:skills"

[navigation.resume]
enabled=true
name="Resume"
icon="qlementine-icons:resume-16"